version: '3.9'

services:

  seq:
    image: datalust/seq:latest
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - 5341:80
    volumes:
        - data:/usr/share/seq/data

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"
    ports:
        - "5001:1433"
    volumes:
      - data:/var/opt/mssql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQL_SERVER_CONNECTION=Server=sqldata; Database=PermissionDb; User=sa;Password=Pass@word;TrustServerCertificate=True;
      - Elasticsearch__Uri=http://elasticsearch:9200
      - Kafka__BootstrapServers=kafka:9092
      - SEQURL=http://seq
    depends_on:
      - elasticsearch
      - kafka
      - sqldata

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
       - zookeeper
       
volumes:
    data: