version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=mydatabase;Uid=root;Pwd=mysecretpassword;
      - Elasticsearch__Uri=http://elasticsearch:9200
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - mysql
      - elasticsearch
      - kafka

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT